# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import core_analysis as ca


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 416)
        MainWindow.setMinimumSize(QtCore.QSize(600, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcone_page = QtWidgets.QWidget()
        self.welcone_page.setObjectName("welcone_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.welcone_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.welcone_page)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.welcone_page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(-1, 24, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(17)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yes_Welcome = QtWidgets.QPushButton(self.frame_3)
        self.yes_Welcome.setMinimumSize(QtCore.QSize(3, 60))
        self.yes_Welcome.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.yes_Welcome.setFont(font)
        self.yes_Welcome.setStyleSheet("QPushButton\n"
                                       "{\n"
                                       "    border:0px;\n"
                                       "    color:#fff;\n"
                                       "    background-color:rgb(46, 204, 113);\n"
                                       "    border-radius:5px\n"
                                       "}\n"
                                       "QPushButton:hover\n"
                                       "{\n"
                                       "    border:0px;\n"
                                       "    font: 20pt \"MS Shell Dlg 2\";\n"
                                       "}")
        self.yes_Welcome.setObjectName("yes_Welcome")
        self.gridLayout_2.addWidget(self.yes_Welcome, 0, 0, 1, 1)
        self.no_Welcome = QtWidgets.QPushButton(self.frame_3)
        self.no_Welcome.setMinimumSize(QtCore.QSize(0, 60))
        self.no_Welcome.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.no_Welcome.setFont(font)
        self.no_Welcome.setStyleSheet("QPushButton\n"
                                      "{\n"
                                      "    border:0px;\n"
                                      "    color:#fff;\n"
                                      "    background-color: rgb(255, 73, 41);\n"
                                      "    border-radius:5px\n"
                                      "}\n"
                                      "QPushButton:hover\n"
                                      "{\n"
                                      "    border:0px;;\n"
                                      "    font: 20pt \"MS Shell Dlg 2\";\n"
                                      "}")
        self.no_Welcome.setObjectName("no_Welcome")
        self.gridLayout_2.addWidget(self.no_Welcome, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2.addWidget(self.frame_4, 0, 2, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_2.addWidget(self.frame_13, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.welcone_page)
        self.Resultpage = QtWidgets.QWidget()
        self.Resultpage.setObjectName("Resultpage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Resultpage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")

        self.email_sent = QtWidgets.QLabel(self.Resultpage)
        self.email_sent.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.email_sent.setFont(font)
        self.email_sent.setObjectName("email_sent")
        
        self.email_sent.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignCenter)
        self.verticalLayout_8.addWidget(self.email_sent)
        
        self.Personality_result = QtWidgets.QLabel(self.Resultpage)
        self.Personality_result.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Personality_result.setFont(font)
        self.Personality_result.setObjectName("Personality_result")
        self.verticalLayout_8.addWidget(self.Personality_result)

        self.scrollArea = QtWidgets.QScrollArea(self.Resultpage)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 941, 325))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.frame_18)
        self.label_9.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_13 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.gridLayout_5.addWidget(self.frame_18, 1, 0, 1, 2)
        self.frame_20 = QtWidgets.QFrame(self.frame_16)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_20)
        self.label_11.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.label_11)
        
        font = QtGui.QFont()
        font.setPointSize(12)

        self.label_15 = QtWidgets.QLabel(self.frame_20)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignCenter)
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.gridLayout_5.addWidget(self.frame_20, 5, 0, 1, 2)
        self.frame_19 = QtWidgets.QFrame(self.frame_16)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_19)
        self.label_10.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.label_14 = QtWidgets.QLabel(self.frame_19)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_14.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.gridLayout_5.addWidget(self.frame_19, 2, 0, 1, 2)
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")

        
        self.frame_177 = QtWidgets.QFrame(self.frame_16)
        self.frame_177.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_177.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_177.setObjectName("frame_177")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.frame_177)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_88 = QtWidgets.QLabel(self.frame_177)
        self.label_88.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_88.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_44.addWidget(self.label_88)
        self.label_122 = QtWidgets.QLabel(self.frame_177)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_122.setFont(font)
        self.label_122.setMinimumSize(QtCore.QSize(0, 0))
        self.label_122.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_122.setWordWrap(True)
        self.label_122.setObjectName("label_122")
        self.horizontalLayout_44.addWidget(self.label_122)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame_17)
        self.label_8.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(self.frame_17)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.gridLayout_5.addWidget(self.frame_17, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame_177, 4, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.frame_16)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 3, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.Resultpage)
        self.singInPage = QtWidgets.QWidget()
        self.singInPage.setObjectName("singInPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.singInPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.singInPage)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.frame_6 = QtWidgets.QFrame(self.singInPage)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout_3.addWidget(self.lineEdit_email, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 2)
        self.valid_email = QtWidgets.QLabel(self.frame_5)
        self.valid_email.setMinimumSize(QtCore.QSize(20, 0))
        self.valid_email.setMaximumSize(QtCore.QSize(16777215, 20))
        self.valid_email.setStyleSheet("color: rgb(255, 0, 0);")
        self.valid_email.setText("")
        self.valid_email.setObjectName("valid_email")
        self.gridLayout_3.addWidget(self.valid_email, 3, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 2)
        self.valid_passs = QtWidgets.QLabel(self.frame_5)
        self.valid_passs.setMinimumSize(QtCore.QSize(22, 0))
        self.valid_passs.setMaximumSize(QtCore.QSize(16777215, 20))
        self.valid_passs.setStyleSheet("color: rgb(255, 0, 0);")
        self.valid_passs.setText("")
        self.valid_passs.setObjectName("valid_passs")
        self.gridLayout_3.addWidget(self.valid_passs, 5, 0, 1, 3)
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout_3.addWidget(self.lineEdit_username, 0, 2, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout_3.addWidget(self.lineEdit_password, 4, 2, 1, 1)
        self.valid_user = QtWidgets.QLabel(self.frame_5)
        self.valid_user.setMinimumSize(QtCore.QSize(12, 0))
        self.valid_user.setMaximumSize(QtCore.QSize(16777215, 20))
        self.valid_user.setStyleSheet("color: rgb(255, 0, 0);")
        self.valid_user.setText("")
        self.valid_user.setObjectName("valid_user")
        self.gridLayout_3.addWidget(self.valid_user, 1, 0, 1, 3)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(341, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(-1, 39, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.pushButtonyes = QtWidgets.QPushButton(self.frame_8)
        self.pushButtonyes.setMinimumSize(QtCore.QSize(0, 65))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButtonyes.setFont(font)
        self.pushButtonyes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonyes.setStyleSheet("QPushButton\n"
                                         "{\n"
                                         "    border:0px;\n"
                                         "    color:#fff;\n"
                                         "    background-color:rgb(46, 204, 113);\n"
                                         "    border-radius:5px\n"
                                         "}\n"
                                         "QPushButton:hover\n"
                                         "{\n"
                                         "    border:0px;\n"
                                         "    font: 20pt \"MS Shell Dlg 2\";\n"
                                         "}")
        self.pushButtonyes.setObjectName("pushButtonyes")
        self.horizontalLayout_2.addWidget(self.pushButtonyes)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.singInPage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setContentsMargins(-1, 0, 20, 22)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setContentsMargins(2, 0, 9, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.questionLabel = QtWidgets.QLabel(self.frame_12)
        self.questionLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.questionLabel.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.questionLabel.setFont(font)
        self.questionLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.questionLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.questionLabel.setObjectName("questionLabel")
        self.verticalLayout_7.addWidget(self.questionLabel)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_7.addWidget(self.frame_14)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.gridLayout_4.addWidget(self.frame_10, 0, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.page)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_3.addWidget(self.frame_15)
        self.pushButtonyes_2 = QtWidgets.QPushButton(self.frame_11)
        self.pushButtonyes_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButtonyes_2.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButtonyes_2.setFont(font)
        self.pushButtonyes_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonyes_2.setStyleSheet("QPushButton\n"
                                           "{\n"
                                           "    border:0px;\n"
                                           "    color:#fff;\n"
                                           "    background-color:rgb(46, 204, 113);\n"
                                           "    border-radius:5px\n"
                                           "}\n"
                                           "QPushButton:hover\n"
                                           "{\n"
                                           "    border:0px;\n"
                                           "    font: 20pt \"MS Shell Dlg 2\";\n"
                                           "}")
        self.pushButtonyes_2.setObjectName("pushButtonyes_2")
        self.horizontalLayout_3.addWidget(self.pushButtonyes_2)
        self.gridLayout_4.addWidget(self.frame_11, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        font4 = QtGui.QFont()
        font4.setPointSize(13)

        self.nochecked = QtWidgets.QLabel(self.frame_15)
        self.nochecked.setObjectName(u"nochecked")
        self.nochecked.setGeometry(QtCore.QRect(40, 0, 441, 60))
        self.nochecked.setMinimumSize(QtCore.QSize(0, 40))
        self.nochecked.setMaximumSize(QtCore.QSize(16777215, 60))
        self.nochecked.setFont(font4)
        self.nochecked.setStyleSheet(u"color: rgb(170, 0, 0);")
        # self.nochecked.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Personality Test"))
        self.label.setText(_translate("MainWindow", "Are you ready to take this test?"))
        self.yes_Welcome.setText(_translate("MainWindow", "Yes"))
        self.no_Welcome.setText(_translate("MainWindow", "No"))
        self.Personality_result.setText(_translate("MainWindow", "label "))
        self.label_9.setText(_translate("MainWindow", "Strengths  "))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Tips"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Weaknesses  "))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Introduction  "))
        self.label_88.setText(_translate("MainWindow", "Career  "))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Show Career and Tips"))
        self.label_2.setText(_translate("MainWindow", "Welcome to the personality test"))
        self.label_3.setText(_translate("MainWindow", "Please enter your username"))
        self.label_5.setText(_translate("MainWindow", "Please enter your password"))
        self.label_4.setText(_translate("MainWindow", "Please enter your email"))
        self.label_6.setText(_translate("MainWindow", "Your password should achieve these conditions:\n"
                                                      "* Minimum 8 characters.\n"
                                                      "* The alphabet must be between [a-z]\n"
                                                      "* At least one alphabet should be of Upper Case [A-Z]\n"
                                                      "* At least 1 number or digit between [0-9].\n"
                                                      "* At least 1 character from [ _ or @ or $ ].\n"
                                                      ""))
        self.pushButtonyes.setText(_translate("MainWindow", "Login"))
        self.questionLabel.setText(_translate("MainWindow", "How are you described?"))
        self.pushButtonyes_2.setText(_translate("MainWindow", "Next"))

        ## logic beginning
        # //////////////////////////////////////////////////////////////////////////////////////////////////
        # self.stackedWidget.setCurrentIndex(3) # init the first widget
        self.userNameFlag = ""
        self.emailFlag = ""
        self.passwordFlag = ""
        self.userType = "" 
        self.analyses = ""

        self.Question_number = 1
        self.answersList = []
        self.radioButtonsList = []
        # init the first question
        self.font5 = QtGui.QFont()
        self.font5.setPointSize(15)
        self.questionLabel.setText(ca.read(self.Question_number)[0])
        for index in range(len(ca.read(self.Question_number))):
            if index != 0:
                self.radioButtonsList.append(QtWidgets.QRadioButton(self.frame_12))
                self.radioButtonsList[index - 1].setObjectName(u"radioButton_2")
                self.verticalLayout_10.addWidget(self.radioButtonsList[index - 1])
                self.radioButtonsList[index - 1].setText(ca.read(self.Question_number)[index])
                self.radioButtonsList[index - 1].setFont(self.font5)

        # ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        # signals for events (such as clicks)
        self.yes_Welcome.clicked.connect(self.welcone_Fun)
        self.no_Welcome.clicked.connect(self.exit_Fun)
        self.pushButtonyes.clicked.connect(self.singIn_Fun)
        self.pushButtonyes_2.clicked.connect(self.questionsAndAnswers)

        #tips button 
        self.clicked = True
        self.frame_20.setVisible(False)
        self.frame_177.setVisible(False)
        self.pushButton.clicked.connect(self.showTipsFun)
    def welcone_Fun(self):
        self.stackedWidget.setCurrentIndex(2)

    def exit_Fun(self):
        exit()

    def singIn_Fun(self):
        # get the value from line edits
        username = self.lineEdit_username.text()
        self.userNameFlag = username
        email = self.lineEdit_email.text()
        self.emailFlag = email
        password = self.lineEdit_password.text()
        self.passwordFlag = password

        f = open("user_data.txt", mode='r')
        for line in f:
            lines = line.strip().split("*")
            if lines[0] == email:
                # if lines[1] == password:
                self.analyses = ca.get_personality_traits(lines[2])

                self.Personality_result.setText(lines[2])
                self.label_12.setText(self.analyses[0][1]) #introduction
                self.label_13.setText(self.analyses[0][3]) # strength
                self.label_14.setText(self.analyses[0][4]) # weakness
                self.label_122.setText(self.analyses[1][1]) # career
                self.label_15.setText(self.analyses[2]) # Tips

                # email_result("ahmedmahmoud95@rocketmail.com", "ESTJ", introduction, strength, weakness, career, tips2)
                ca.email_result(self.emailFlag,lines[2],self.analyses[0][1],self.analyses[0][3],self.analyses[0][4],self.analyses[1][1],self.analyses[2])
                self.email_sent.setText("We have sent you an email, go and check your personality characteristics.")

                self.stackedWidget.setCurrentIndex(1)
                # else:
                #     self.valid_email.setText("the email already exists")
                #     self.valid_passs.setText("Please enter the password to show th results"    
                break

        if len(username) == 0 or " " in username:
            self.valid_user.setText("Please enter a valid name")
            if email != ca.email_validation(email):
                self.valid_email.setText(ca.email_validation(email))
            else:
                self.valid_email.setText("")
            if password != ca.password_validation(password):
                self.valid_passs.setText("Please enter a valid password")
            else:
                self.valid_passs.setText("")
        else:
            self.valid_user.setText("")
            if email == ca.email_validation(email):
                self.valid_email.setText("")
            if email != ca.email_validation(email):
                self.valid_email.setText(ca.email_validation(email))
            if password == ca.password_validation(password):
                self.valid_passs.setText("")
            if password != ca.password_validation(password):
                self.valid_passs.setText("Please enter a valid password")
            if email == ca.email_validation(email) and password == ca.password_validation(password):
                self.stackedWidget.setCurrentIndex(3)

    def clear_tab(self):
        """
            when u gonna add another question u gonna need to clear the Layout
            from the existing radio buttons
        """
        self.nochecked.setText("")
        while self.verticalLayout_10.count():
            child = self.verticalLayout_10.takeAt(0)
            if child.widget():
                child.widget().deleteLater()

    def questionsAndAnswers(self):
        if self.Question_number == 19:
            self.pushButtonyes_2.setText("Finish")
        if self.Question_number < 20:
            theresNoCheckedAnswer = True  # check if there
            try:
                for index in range(len(self.radioButtonsList)):
                    if self.radioButtonsList[index].isChecked():
                        self.answersList.append(self.radioButtonsList[index].text())
                        theresNoCheckedAnswer = False
            except:
                self.nochecked.setText("please choose an answer")
            if theresNoCheckedAnswer == False:
                self.radioButtonsList = []
                self.clear_tab()
                if len(self.answersList) == self.Question_number:
                    self.Question_number = self.Question_number + 1
                self.questionLabel.setText(ca.read(self.Question_number)[0])
                for index in range(len(ca.read(self.Question_number))):
                    if index != 0:
                        self.radioButtonsList.append(QtWidgets.QRadioButton(self.frame_12))
                        self.radioButtonsList[index - 1].setObjectName(u"radioButton_2")
                        self.verticalLayout_10.addWidget(self.radioButtonsList[index - 1])
                        self.radioButtonsList[index - 1].setText(ca.read(self.Question_number)[index])
                        self.radioButtonsList[index - 1].setFont(self.font5)

            else:
                self.nochecked.setText("please choose an answer")
        else:
            self.userType = ca.signup(self.userNameFlag,self.emailFlag,self.passwordFlag,self.answersList)
            self.analyses = ca.get_personality_traits(self.userType)

            self.Personality_result.setText(self.userType)
            self.label_12.setText(self.analyses[0][1]) #introduction
            self.label_13.setText(self.analyses[0][3]) # strength
            self.label_14.setText(self.analyses[0][4]) # weakness
            self.label_122.setText(self.analyses[1][1]) # career
            self.label_15.setText(self.analyses[2]) # Tips

            # email_result("ahmedmahmoud95@rocketmail.com", "ESTJ", introduction, strength, weakness, career, tips2)
            ca.email_result(self.emailFlag,self.userType,self.analyses[0][1],self.analyses[0][3],self.analyses[0][4],self.analyses[1][1],self.analyses[2])

            self.stackedWidget.setCurrentIndex(1)
        # ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        # logic end
    def showTipsFun(self):
        if self.clicked:
            self.frame_20.setVisible(True)
            self.frame_177.setVisible(True)
            
            # self.pushButton.setVisible(False)
            self.pushButton.setText("Hide Career and Tips")
            self.clicked = False
        else:
            self.frame_20.setVisible(False)
            self.frame_177.setVisible(False)
            self.pushButton.setText("Show Career and Tips")
            self.clicked = True
            # self.pushButton.setVisible(False)



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())